"""included upload_type in the log

Revision ID: 6587fe788df6
Revises: 
Create Date: 2025-09-28 16:28:16.262689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6587fe788df6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_upload_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_upload_log', schema=None) as batch_op:
        batch_op.drop_column('upload_type')

    # ### end Alembic commands ###
