"""Changed field in the bulk upload error log

Revision ID: dc481cfdee84
Revises: 6587fe788df6
Create Date: 2025-09-28 16:31:35.935942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc481cfdee84'
down_revision = '6587fe788df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_upload_error', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=500), nullable=False))
        batch_op.drop_column('error_message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_upload_error', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_message', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
